---

- name: install docker
  apt: pkg=docker.io state=installed

# Add a line to a file if it does not exist, without passing regexp
- name: configure docker to listen on eth2 ipv4 address instead of a socket
  lineinfile: dest=/etc/default/docker.io line="DOCKER_OPTS=\"-H tcp://127.0.0.1:4243 -H unix:///var/run/docker.sock\""
  register: docker_host
  notify: restart docker

- name: restart docker
  service: name=docker.io state=restarted
  when: docker_host.changed

- name: wait for docker on private ip port 4243
  wait_for: port=4243 delay=15 host=127.0.0.1
  when: docker_host.changed

- debug: msg="docker is up and listening on port 4243"